### ISSUE TITLE
A question about SCORE_THRESH setting of POST_PROCESSING

### ISSUE THREAD

**Issue by Viczyf** [hlsheng1/CT3D#6]
Thanks for your great work;
How do you set SCORE_THRESH when you train the model on all trainsets and submit the prediction results to the KITTI benchmark evaluation? 0.7 or 0.81? 
By the way, what's the insight for changing the score_thresh? I guess that you did it to remove some false positive predictions.

**Comment by hlsheng1** [comment]
@Viczyf For KITTI test submission, SCORE_THRESH for car is set as 0.7+（seems 0.72）. The result of KITTI testboard will first increase slowly and then decrease abruptly as the threshold value becomes larger. 
Yes, the score_thresh is used for removing smoe unreasonable predictions, no matter how big the value is set. For our methos, we found the output score of true positive predictions are usually 0.9+, so I could set a slightly larger score_thresh. I think the setting of score_thresh may change the boundary value of the sampling point of the PR curve, and that's why the results changes.

**Comment by Viczyf** [comment]
Thanks for your reply
